@echo off

echo Starting product-service...
start "product-service" cmd /k "cd /d product-service && mvn spring-boot:run"

echo Starting auth-service...
start "auth-service" cmd /k "cd /d auth-service && mvn spring-boot:run"

echo Starting api-gateway...
start "api-gateway" cmd /k "cd /d api-gateway && mvn spring-boot:run"

echo All services are starting...